categories:
  - title: '⭐ New Features'
    label: 'type: enhancement'
  - title: '🐞 Bug Fixes'
    label: 'type: bug'
  - title: '📔 Documentation'
    label: 'type: documentation'
  - title: '🔨 Dependency Upgrades'
    label: 'type: dependency-upgrade'

change-template: '* $TITLE #$NUMBER'
template: |

  $CHANGES
  
  ❤️ Contributors
  
  We'd like to thank all the contributors who worked on this release!
  
  $CONTRIBUTORS
