categories:
  - title: '⚠️ Breaking changes'
    label: 'breaking-change'
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🛠️ Maintenance'
    labels: ['chore', 'refactor', 'style']
  - title: '📝 Documentation'
    label: 'documentation'
  - title: '🧪 Tests'
    label: 'test'

exclude-labels:
  - 'skip-changelog'
template: |
  ## What's Changed

  $CHANGES
