name: "Bug Report"
description: Create a report to help us improve
labels: [
  "status: waiting-for-triage",
  "type: bug",
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Version"
      description: The version of the package you are using.
      placeholder: "e.g. 1.0.0"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: The operating system you are using.
      options:
        - Linux
        - MacOS
        - Windows
    validations:
      required: true
